workflows:
  android-build:
    name: Android Build
    environment:
      java: 17
    scripts:
      - name: Build APK
        script: |
          # Make gradlew executable
          chmod +x gradlew
          
          # Build debug APK
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      artifacts:
        - app/build/outputs/**/*.apk
